### ISSUE TITLE
Addition of TravisCI to improve the code quality

### ISSUE THREAD

**Issue by TheMeinerLP** [TheMadfixLab/CloudNet-WebInterface#11]
**Description of the new feature:**

By adding travis ci we can check in future pull requests and more. Through this basic implementation we can produce a very continuous code quality.

**Reasons for inclusion into the web interface code base:**

Modular is not possible because this is a file in the repository and not source code

**Planned audience:**

The function is in the first sense for developers, but is also interesting for users 

**Preview of code and documentation:**

```yml
language: java
dist: bionic
sudo: false
notifications:
  email: false  
```

**Additional context:**
